### ISSUE TITLE
Задачи 1.2.16 + 1.2.17. Robust implementation of rational numbers

### ISSUE THREAD

**Issue by be9** [derokarf/rep1#14]
**1.2.16.** Implement an immutable data type `Rational` for rational numbers that supports addition, subtraction, multiplication, and division.

```java
public class Rational {
    Rational(int numerator, int denominator) { ... }
    Rational plus(Rational b) { ... }         // sum of this number and b
    Rational minus(Rational b) { ... }        // difference of this number and b
    Rational times(Rational b) { ... }        // product of this number and b
    Rational divides(Rational b) { ... }      // quotient of this number and b
    boolean equals(Rational that) { ... }     // is this number equal to that?
    String toString() { ... }                 // string representation
```
You do not have to worry about testing for overflow (see Exercise 1.2.17), but use as instance variables two `long` values that represent the numerator and denominator to limit the possibility of overflow. Use Euclid’s algorithm (see page 4) to ensure that the numerator and denominator never have any common factors. Include a test client that exercises all of your methods.

**1.2.17.** Use assertions to develop an implementation of Rational (see Exercise 1.2.16) that is immune to overflow.

**Comment by derokarf** [comment]
Вопрос по 1.2.17. Мы оставляем два поля типа long и просто контролируем их с помощью assert или мы меняем их на int и контролируем до присваивания?

**Comment by be9** [comment]
@derokarf Думаю, long + assert.
