### ISSUE TITLE
Задача 1.1.27. Binomial distribution

### ISSUE THREAD

**Issue by be9** [derokarf/rep1#2]
Estimate the number of recursive calls that would be used by the code

```java
    public static double binomial(int N, int k, double p)
    {
       if ((N == 0) || (k < 0)) return 1.0;
       return (1.0 - p)*binomial(N-1, k) + p*binomial(N-1, k-1);
    }
```
to compute `binomial(100, 50)`. Develop a better implementation that is based on saving computed values in an array.

**Comment by derokarf** [comment]
`return (1.0 - p)*binomial(N-1, k) + p*binomial(N-1, k-1);`
Я правильно понимаю, тут сначала сам код в порядок нужно привести? Т.к. binomial требует три аргумента на вход, а в указанной строке ему передается 2.

**Comment by be9** [comment]
@derokarf А сколько всё-таки будет рекурсивных вызовов у `binomial(100, 50, p)` в этой плохой реализации?
