### ISSUE TITLE
1.4.12

### ISSUE THREAD

**Issue by be9** [derokarf/rep1#26]
Write a program that, given two sorted arrays of _N_ int values, prints all elements that appear in both arrays, in sorted order. The running time of your program should be proportional to _N_ in the worst case.

**Comment by derokarf** [comment]
Олег, вопрос. К примеру,
Первый массив 1 7 11 11 19
Второй массив 1 1 4 7 9 11 14 16 17
Мы должны вывести
1) 1 7 11 
или
2) 1 1 1 7 7 11 11 11
?

**Comment by be9** [comment]
@derokarf первое.
