### ISSUE TITLE
1.4.16&17

### ISSUE THREAD

**Issue by be9** [derokarf/rep1#27]
_Closest pair (in one dimension)._ Write a program that, given an array `a[]` of _N_ double values, finds a _closest pair_: two values whose difference is no greater than the the difference of any other pair (in absolute value). The running time of your program should be linearithmic in the worst case.

_Farthest pair (in one dimension)._ Write a program that, given an array `a[]` of _N_ double values, finds a _farthest pair_: two values whose difference is no smaller than the the difference of any other pair (in absolute value). The running time of your program should be linear in the worst case.

**Comment by derokarf** [comment]
Олег, я очень сильно туплю. Я два дня бился с алгоритмом ближайшей пары и ничего не придумал :( .  Намекни, пожалуйста - там используется среднее арифметическое значение элементов массива?
P.S. Самую далекую пару я сделал.

**Comment by derokarf** [comment]
Олег, извини за беспокойство. Уже не нужны подсказки, я, вроде, нашел решение :).

**Comment by be9** [comment]
А я как раз собирался писать подсказку. В общем, если хватит не линейного, а квазилинейного (linearithmic) времени, то с массивом всегда можно кое-что сначала сделать 😉
