### ISSUE TITLE
1.4.32. Amortized analysis

### ISSUE THREAD

**Issue by be9** [derokarf/rep1#29]
Prove that, starting from an empty stack, the number of array accesses used by any sequence of _M_ operations in the resizing array implementation of `Stack` is proportional to _M_.

**Comment by derokarf** [comment]
Олег, что я здесь неправильно понимаю?
Страница 199.
N + 4 + 8 + 16 + ... + 2N = 5N - 4
Как получена правая часть?
У меня число обращений к элементам массива для N операций получается 2N-1, т.е. N добавлений в стек плюс сумма копируемых элементов при удвоении, которая так же будет равна N. Где я неправильно считаю?

**Comment by derokarf** [comment]
Я здесь просто не понимаю вот чего. Да, для N+1 последовательных операций, есть N операций с постоянным временем (O(1))и одна операция со временем N ( O(N)). Как я понимаю, из доказательства (на той же странице) - мы берем отношение времени операции удвоения к количеству операций всего и получаем некую константу,так? Т.е. (O(N)/N+1). Я тут не понимаю почему мы пренебрегаем операциями с постоянным временем. Она же не одна, их же N. Понятно что запись элемента в массив есть операция с постоянным временем, но ведь запись всего массива уже будет O(N)?

**Comment by derokarf** [comment]
Я правильно понимаю:
- есть стек List, (изначально пустой и реализованный через массив переменной длины)
- со стеком List выполняют M каких то операций
- нужно доказать что количество обращений к массиву внутри реализации стека List, при выполнении этих M операций, пропорционально самому М
Так звучит задание?

P.S. Олег, прошу прощения, но как то тяжело мне это задание дается :(

**Comment by be9** [comment]
Да, задача — это продолжение доказательства, которое мы рассматривали выше. Они доказали, что, если делать *M* вставок, то общее количество операций доступа будет *~ M*. А теперь предположим, что у нас не *M* вставок, а *M* произвольных операций, т.е. произвольного сочетания push и pop...
