### ISSUE TITLE
Задачи 1.5.5 и 1.5.6

### ISSUE THREAD

**Issue by be9** [derokarf/rep1#34]
**1.5.5.** Estimate the minimum amount of time (in days) that would be required for quick-find to solve a dynamic connectivity problem with 10<sup>9</sup> sites and 10<sup>6</sup> input pairs, on a computer capable of executing 10<sup>9</sup> instructions per second. Assume that each iteration of the inner for loop requires 10 machine instructions.

**1.5.6.** Repeat Exercise 1.5.5 for weighted quick-union.

Ответ можно прямо здесь, не надо ничего коммитить.

**Comment by derokarf** [comment]
1.5.5 - Цикл for в union и есть наименее рациональная часть алгоритма. И нам как раз известна только его трудоемкость по условию задачи. Пусть, к примеру, входные пары будут непересекающимися, т.е. "наихудший случай". Тогда цикл постоянно будет перебиратьвесь массив. Т.е. необходимо будет 106*109*10 = 115540 иструкций для его выполнения. Отсюда на обработку всех пар понадобится 115540/109 = 1060 сек. или 17.6 минут
1.5.6 - Этот метод труднее оценивать, т.к. сложность не так сильно перевешивает в какой то точке алгоритма. Наиболее сложная здесь операция поиска. Если принять стоимость каждой ее итерации за те же самые 10 инструкций, то получим (два поиска на одно объединение) (2*(2N-1)) -> 2*217*10 = 4340 инструкций. Т.е. понадобится ~ 40 секунд. 
P.S. Олег, упоминание в задании единиц измерения в "днях" меня смущает и заставляет думать о неправильном решении :))). Я, кстати, запускал эти реализации на парах 1-2,2-3,3-4 с добавленным счетчиком инструкции, результаты с теорией у меня совпадали.

**Comment by be9** [comment]
@derokarf а, ну это я плохо скопировал. Там не 109 и 106, а 10^9 и 10^6. Повтори свои вычисления для этих значений (текст я поправил). Кстати, в задаче предлагается оценить минимальное время, т.е. наилучший, а не наихудший случай.

**Comment by derokarf** [comment]
Это не только ты плохо скопировал - в русском переводе именно так и написано 109 и 106... А я оригинал как то не глянул. Понял, сделаю.

**Comment by derokarf** [comment]
1.5.5 Хорошо. Пусть будет лучший случай. Решим немного обратную задачу. Для получения  ~ 10<snap>6</snap> уникальных пар, необходимо ~ 1414 узлов. Тогда из 10<snap>6</snap> пар внутренний цикл будет работать в 1413 случаях, все остальные пары будут уже соединены. Следовательно, понадобится 1413*10<snap>9</snap>*10/10<snap>9</snap>  = 14130 секунд или ~4 часа.
1.5.6 Аналогичная стратегия лучшего случая.  (2*(2N-1)) = 2*(2*1413) = 5652 -> 5652*10 = 56520 инструкций, т.е. время выполнения 0.00005652 сек.

**Comment by be9** [comment]
**1.5.5.** По всей видимости, под "minimum time" Седжвик всё же имеет в виду время кручения в цикле без учёта остального. Т.е. нет предположений об уникальности пар и прочем. В таком разе у меня получилось 115 дней. Но для частного случая твоё решение верное.

**1.5.6.** Здесь для общего случая получилось 0,3 сек.

Попробуй повторить мои цифры, и покончим с этой задачей.

**Comment by derokarf** [comment]
1.5.5. Тут все просто: 10<sup>6</sup> * 10<sup>9</sup> * 10/10<sup>9</sup> = 10<sup>7</sup>/86400 ~ 115 дней
1.5.6. Тут не все просто. Как-то так, думаю: (10*(10<sup>6</sup>-1)lg10<sup>6</sup>)/10<sup>9</sup> ~ 0.2 сек

**Comment by derokarf** [comment]
P.S. Как то неуютно себя чувствуешь после всех этих неточностей/неясностей в заданиях. Но особенно в теоретической части. Вместо того чтобы заниматься реализацией - начинаешь перепроверять теорию, выдаваемую авторами. Хотя, может это только у меня такие проблемы.

**Comment by derokarf** [comment]
Я не говорю что книга плохая. Она очень-очень даже хороша. Все описано компактно, много интересных мыслей и заданий. Но (это только мое мнение) - для использования ее в качестве учебника нужно доработать теоретическую часть. Проверить, уточнить, дополнить.

**Comment by be9** [comment]
Увы, книга такова, какая есть.
