### ISSUE TITLE
Задача 1.5.20. Dynamic growth

### ISSUE THREAD

**Issue by be9** [derokarf/rep1#36]
Using linked lists or a resizing array, develop a weighted quick-union implementation that removes the restriction on needing the number of objects ahead of time. Add a method `newSite()` to the API, which returns an `int` identifier.

**Comment by derokarf** [comment]
Я тут немного голову сломал. Вопрос - мы можем немного увеличить вычислительную сложность реализации? Т.к. поиск по связным спискам тоже несколько затратная операция, они же не индексированы. Т.е. я бы хотел прикрутить к связным спискам что то вроде бинарного поиска, для получения эквивалента операции "id[p]=".

**Comment by derokarf** [comment]
Немного непонятно, что должен делать newSite(). Возвращать индекс узла в дереве, следующий за текущим?

**Comment by be9** [comment]
Я бы предложил использовать динамический массив. Со списками нужно создавать дополнительную структуру данных — отображение ID в элемент списка.

Что касается `newSite()`, то это нужно для получения ID нового site.
