### ISSUE TITLE
Задачи 2.1.6 и 2.1.7

### ISSUE THREAD

**Issue by be9** [derokarf/rep1#40]
**2.1.6.** Which method runs faster for an array with all keys identical, selection sort or insertion sort?

**2.1.7.** Which method runs faster for an array in reverse order, selection sort or insertion sort?

Ответы с обоснованием — здесь в комментариях.

**Comment by derokarf** [comment]
2.1.6 - сортировка вставками будет быстрее, т.к. у нее при одинаковых ключах (так же как и при заранее упорядоченном массиве) будет сразу же тормозиться внутренний цикл перебора "подмассива".
2.1.7 - сортировка выбором будет быстрее, т.к. для сортировки вставками такой массив - "худший случай". при одинаковом количестве сравнений, у сортировки выбором будет N перестановок, а для сортировки вставками понадобится N<sup>2</sup>/2 перестановок.

**Comment by be9** [comment]
👍
