### ISSUE TITLE
Задача 2.1.15. Expensive exchange

### ISSUE THREAD

**Issue by be9** [derokarf/rep1#43]
A clerk at a shipping company is charged with the task of rearranging a number of large crates in order of the time they are to be shipped out. Thus, the cost of compares is very low (just look at the labels) relative to the cost of exchanges (move the crates). The warehouse is nearly full—there is extra space sufficient to hold any one of the crates, but not two. What sorting method should the clerk use?

Ответ — в комментарии.

**Comment by derokarf** [comment]
Сортировка выбором. У нее самое меньшее гарантированное число перестановок.
P.S. Немного не понял, зачем указание на то, что есть только одно свободное место,  а не два? Ведь все эти три перестановки используют обмен пары ключе, а для этого одной свободной ячейки достаточно?

**Comment by be9** [comment]
Про два места не знаю. Думаю, имелось в виду заставить использовать именно описанные в этой главе методы. Но рассуждения верные. 👍
